language: php
sudo: false
php:
  - 7.0
install:
  - composer self-update
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php coveralls.phar
